### ISSUE TITLE
Investigate failures in onboarding.massopen.cloud application credentials UI

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#4]
Attempts to create new application credentials currently fail with:

```
Danger: There was an error submitting the form. Please try again" (and does not create credentials
```

**Comment by larsks** [comment]
This doesn't appear to be related to the problem we resolved in #9.

**Comment by larsks** [comment]
We're seeing the following traceback in the horizon logs on the SSO servers:

```
ERROR django.request Internal Server Error: /identity/create/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/horizon/horizon/decorators.py", line 52, in dec
    return view_func(request, *args, **kwargs)
  File "/opt/horizon/horizon/decorators.py", line 36, in dec
    return view_func(request, *args, **kwargs)
  File "/opt/horizon/horizon/decorators.py", line 36, in dec
    return view_func(request, *args, **kwargs)
  File "/opt/horizon/horizon/decorators.py", line 113, in dec
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 382, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 409, in _clean_form
    cleaned_data = self.clean()
  File "/opt/horizon/openstack_dashboard/dashboards/identity/application_credentials/forms.py", line 138, in clean
    cleaned_data['access_rules'])
KeyError: 'access_rules'
```

**Comment by larsks** [comment]
@knikolla it looks like the `access_rules` key is explicitly deleted for older versions of keystone in [line 72](https://github.com/openstack/horizon/blob/master/openstack_dashboard/dashboards/identity/application_credentials/forms.py#L72):

```
        if keystone_version < (3, 13):
            del self.fields['access_rules']
```

But the `clean` method doesn't know about that:

```
    def clean(self):
        cleaned_data = super().clean()
        try:
            cleaned_data['access_rules'] = yaml.safe_load(
                cleaned_data['access_rules'])
        except yaml.YAMLError:
            msg = (_('Access rules must be a valid JSON or YAML list.'))
            raise forms.ValidationError(msg)
        return cleaned_data
```

This looks like a horizon bug. The solution is probably to wrap the `try/except` block with an `if 'access_rules' in cleaned_data:` block.

**Comment by larsks** [comment]
I patched `/opt/horizon/openstack_dashboard/dashboards/identity/application_credentials/forms.py` on both sso1 and sso2, and now I'm able to create application credentials.

New problem:

The `clouds.yaml` provided by the web ui is incorrect. It has:

```
auth_url: https://kaizen.massopen.cloud:13000/
```

But it apparently needs:

```
auth_url: https://kaizen.massopen.cloud:13000/v3
```

**Comment by larsks** [comment]
It looks as if `OPENSTACK_KEYSTONE_URL` in the horizon container is set correctly to `https://kaizen.massopen.cloud:13000/v3`.

The keystone endpoint in the service catalog is set to `https://kaizen.massopen.cloud:13000`, but it seems that ought to be unversioned. I think I'll need to wait for @knikolla to resolve this one.

**Comment by larsks** [comment]
I've submitted the patch for this upstream at https://review.opendev.org/#/c/761027/
