### ISSUE TITLE
Install and configure OCS on ocp-staging

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#446]
I have already taken care of creating the ceph pool and the secret in aws for rook-ceph-external-cluster details. This needs to be done after the network configuration #445

**Comment by larsks** [comment]
There were two noobaa pods failing to schedule because...

```
  Warning  FailedScheduling  115m  default-scheduler  0/5 nodes are available: 2 node(s) didn't match Pod's node affinity/selector, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
```

Looking at the affinity selector in the pod...

```
$ oc get pod noobaa-core-0 -o yaml | yq .spec.affinity -y
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: Exists
```

...we see that the pod will only schedule on nodes that have the `cluster.ocs.openshift.io/openshift-storage` label. I set this on the two worker nodes, and now the noobaa pods are running. The only problem is the `ocs-operator-...` pod:

```
NAME                                            READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-5r8xn                          3/3     Running   0          117m
csi-cephfsplugin-9lj6q                          3/3     Running   0          117m
csi-cephfsplugin-provisioner-655dfccfdf-6lf9z   6/6     Running   0          117m
csi-cephfsplugin-provisioner-655dfccfdf-wshmr   6/6     Running   0          117m
csi-rbdplugin-6mzn6                             3/3     Running   0          117m
csi-rbdplugin-lflp6                             3/3     Running   0          117m
csi-rbdplugin-provisioner-6c8fc7c78b-qh96h      6/6     Running   0          117m
csi-rbdplugin-provisioner-6c8fc7c78b-xl26t      6/6     Running   0          117m
noobaa-core-0                                   1/1     Running   0          103s
noobaa-db-pg-0                                  1/1     Running   0          63s
noobaa-operator-74966b468d-khdk6                1/1     Running   0          117m
ocs-metrics-exporter-56f489d6fb-lz5k9           1/1     Running   0          117m
ocs-operator-54f6b876b8-49nks                   0/1     Running   0          96m
rook-ceph-operator-5ff77bfd-r8znx               1/1     Running   0          117m
```

Looking at the logs there it seems to be complaining about the storagecluster resource:

```
{"level":"error","ts":1636593056.6943364,"logger":"controller-runtime.manager.controller.storagecluster","msg":"Reconciler error","reconciler group":"ocs.openshift.io","reconciler kind":"StorageCluster","name":"ocs-external-storagecluster","namespace":"openshift-storage","error":"Operation cannot be fulfilled on storageclusters.ocs.openshift.io \"ocs-external-storagecluster\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/remote-source/app/vendor/github.com/go-logr/zapr/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/remote-source/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:297\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/remote-source/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:248\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/remote-source/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/remote-source/app/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/remote-source/app/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/remote-source/app/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/remote-source/app/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/remote-source/app/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/remote-source/app/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99"}
```

**Comment by larsks** [comment]
Despite the operator errors, it looks as if OCS is functional. I was able to create a PVC and it was immediately bound to a PV.

**Comment by naved001** [comment]
@larsks do you think we can close this issue then?

**Comment by larsks** [comment]
I think we should probably figure out what's going on with the operator, but if you'd prefer we can close this and open a new issue specific to that problem.

**Comment by naved001** [comment]
I should be able to create object bucket claims, right?

and looks like that's not working either
```
naved@naved-MS-7984:~$ oc get obc -n openshift-storage
NAME             STORAGE-CLASS                 PHASE     AGE
naved-deleteme   openshift-storage.noobaa.io   Pending   2m
```

**Comment by naved001** [comment]
https://noobaa-mgmt-openshift-storage.apps.ocp-staging.massopen.cloud/fe/  says its upgrading.

I looked at `noobaa-core-0` logs, and saw these error messages
```
Nov-12 11:07:38.309 [BGWorkers/30]    [L0] core.server.bg_services.cluster_hb:: no local cluster info. HB is not written
Nov-12 11:07:39.959 [WebServer/34] [ERROR] core.server.system_services.system_store:: SystemStore: load failed Error: NON_EXISTING_ROOT_KEY
    at MasterKeysManager.load_root_key (/root/node_modules/noobaa-core/src/server/system_services/master_key_manager.js:64:40)
    at /root/node_modules/noobaa-core/src/server/system_services/system_store.js:427:47
    at Semaphore.surround (/root/node_modules/noobaa-core/src/util/semaphore.js:40:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

`NON_EXISTING_ROOT_KEY`, and came across https://bugzilla.redhat.com/show_bug.cgi?id=2019577

> I think we should probably figure out what's going on with the operator, but if you'd prefer we can close this and open a new issue specific to that problem.

@larsks Let's just stick with this issue since it's not just an operator problem.

**Comment by naved001** [comment]
> NON_EXISTING_ROOT_KEY, and came across https://bugzilla.redhat.com/show_bug.cgi?id=2019577

I followed that bugzilla and deleted the master-root-key as suggested at the end, and that fixed it. I can create object buckets just fine, and the noobaa dashboard is available.

**Comment by naved001** [comment]
the ocs-operator seems to be running too:

```
naved@naved-MS-7984:~$ oc get pods
NAME                                               READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-5r8xn                             3/3     Running   0          44h
csi-cephfsplugin-9lj6q                             3/3     Running   0          44h
csi-cephfsplugin-provisioner-655dfccfdf-6lf9z      6/6     Running   0          44h
csi-cephfsplugin-provisioner-655dfccfdf-wshmr      6/6     Running   0          44h
csi-rbdplugin-6mzn6                                3/3     Running   0          44h
csi-rbdplugin-lflp6                                3/3     Running   0          44h
csi-rbdplugin-provisioner-6c8fc7c78b-qh96h         6/6     Running   0          44h
csi-rbdplugin-provisioner-6c8fc7c78b-xl26t         6/6     Running   0          44h
noobaa-core-0                                      1/1     Running   0          12m
noobaa-db-pg-0                                     1/1     Running   0          42h
noobaa-default-backing-store-noobaa-pod-733d5100   1/1     Running   0          11m
noobaa-endpoint-796d564c6b-rmd7v                   1/1     Running   0          11m
noobaa-operator-74966b468d-khdk6                   1/1     Running   0          44h
ocs-metrics-exporter-56f489d6fb-lz5k9              1/1     Running   0          44h
ocs-operator-54f6b876b8-49nks                      1/1     Running   0          44h
rook-ceph-operator-5ff77bfd-r8znx                  1/1     Running   0          44h
```

**Comment by larsks** [comment]
@naved001 good find on that bugzilla!

**Comment by naved001** [comment]
I am going to close this issue then.
