### ISSUE TITLE
massopen.cloud not responding

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#479]
massopen.cloud is not responding.  msd gathering info and passwords, will update here.   

Spoke with siteground who a pointing the finger at elementor (plug in).    in the process of getting into our elementor account.  
[php_errorlog.txt](https://github.com/CCI-MOC/ops-issues/files/7974268/php_errorlog.txt)

**Comment by msdisme** [comment]
Doing a restore to files and databases from friday to see if that fixes.  May also be related to an update to wordpress.

**Comment by msdisme** [comment]
rolling back to friday seems to have resolved the problem.  closing for now.

**Comment by larsks** [comment]
There are php stack traces in our `php_errorlog`. Some examples:

```
[30-Jan-2022 19:05:31 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/customer/www/massopen.cloud/public_html/wp-includes/class-wp-hook.php(303): Elementor\Mod in /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/core/wp-api.php on line 26
[31-Jan-2022 19:51:17 UTC] wp_auto_login: trying to login user_id==1 loginusername=gmantica to admin_url=https://massopen.cloud/wp-admin/
[31-Jan-2022 21:10:31 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/customer/www/massopen.cloud/public_html/wp-includes/class-wp-hook.php(307): Elementor\Mod in /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/core/wp-api.php on line 26
[01-Feb-2022 19:57:32 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api->get_plugins()
#1 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_with_header()
#2 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module->get_plugins_to_check()
#3 /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module->get_plugins_to_check()
#4 /home/customer/www/massopen.cloud/public_html/wp-includes/class-wp-hook.php(307): Elementor\Mod in /home/customer/www/massopen.cloud/public_html/wp-content/plugins/elementor/core/wp-api.php on line 26
```

**Comment by larsks** [comment]
@msd I've rolled back the site and selected the "skip update" button, which will prevent the update from WordPress 5.8.3 to 5.9. We can use the staging site to confirm the update is safe (or not).

**Comment by larsks** [comment]
Huh, it seems to have updated *anyway*, but the problem isn't reproducing.

**Comment by msdisme** [comment]
Lars restored from security->backups and then did updates of plugins, disabled updates for 5.8.3 worpress to 5.9 and keeping an eye on it.
