### ISSUE TITLE
End Cron Daemon error messages

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#884]
I believe this document explains how the moc-tools work: https://docs.massopen.cloud/en/archive-20220323/archives-page/Helpdesk-Automation.html?highlight=set-quotas.py

Please turn off the process generating this error:

Traceback (most recent call last):
 File "/usr/local/src/moc-tools/production/set-quotas.py", line 199, in <module>
   all_ks_projects = keystone.projects.list()
 File "/usr/lib/python2.7/site-packages/positional/__init__.py", line 108, in inner
   return wrapped(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/keystoneclient/v3/projects.py", line 119, in list
   **kwargs)
 File "/usr/lib/python2.7/site-packages/keystoneclient/base.py", line 75, in func
   return f(*args, **new_kwargs)
 File "/usr/lib/python2.7/site-packages/keystoneclient/base.py", line 390, in list
   self.collection_key)
 File "/usr/lib/python2.7/site-packages/keystoneclient/base.py", line 125, in _list
   resp, body = self.client.get(url, **kwargs)
 File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 304, in get
   return self.request(url, 'GET', **kwargs)
 File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 463, in request
   resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 189, in request
   return self.session.request(url, method, **kwargs)
 File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 573, in request
   auth_headers = self.get_auth_headers(auth)
 File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 900, in get_auth_headers
   return auth.get_headers(self, **kwargs)
 File "/usr/lib/python2.7/site-packages/keystoneauth1/plugin.py", line 90, in get_headers
   token = self.get_token(session)
 File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 89, in get_token
   return self.get_access(session).auth_token
 File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 135, in get_access
   self.auth_ref = self.get_auth_ref(session)
 File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/v3/base.py", line 165, in get_auth_ref
   authenticated=False, log=False, **rkwargs)
 File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 848, in post
   return self.request(url, 'POST', **kwargs)
 File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 698, in request
   resp = send(**kwargs)
 File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 760, in _send_request
   raise exceptions.SSLError(msg)
keystoneauth1.exceptions.connection.SSLError: SSL exception connecting to https://kaizen.massopen.cloud:13000/v3/auth/tokens: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
_______________________________________________
admin mailing list
admin@lists.massopen.cloud
https://mail.massopen.cloud/mailman/listinfo/admin

**Comment by msdisme** [comment]
at:  https://mail.massopen.cloud/mailman/admin/admin/privacy/sender I am blocking moc-tools@helpdeskvm.massopen.cloud for now

**Comment by msdisme** [comment]
Also had it discard and not forward to list owner
