### ISSUE TITLE
XDMoD OpenShift job occasionally errors out

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/ops-issues#957]
Currently, the job has passed for 6/1, 6/2, and 6/4; however 6/3 has errored out with a database error:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 246, in _open_connection
self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'mariadb:3306' (110)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/xdmod-get-config-files", line 80, in <module>
main()
File "/app/xdmod-get-config-files", line 60, in main
cnx = connect_to_db(config)
File "/app/xdmod-get-config-files", line 26, in connect_to_db
cnx = mysql.connector.connect(host=host, user=admin_acct, password=admin_pass)
File "/usr/local/lib/python3.9/site-packages/mysql/connector/__init__.py", line 272, in connect
return CMySQLConnection(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 94, in __init__
self.connect(**kwargs)
File "/usr/local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1052, in connect
self._open_connection()
File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 251, in _open_connection
raise errors.get_mysql_exception(msg=exc.msg, errno=exc.errno,
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mariadb:3306' (110)
cp: cannot stat '/etc/xdmod/clouds.yaml': No such file or directory
```

**Comment by tzumainn** [comment]
@rob-baron any idea why this might occasionally happen?

**Comment by rob-baron** [comment]
I was getting a similar error - the cannot connect to MySQL, as the data directory was filling up.  have increased it to 100Gi, so it should be good until my change to 1000Gi goes though (in review)

**Comment by tzumainn** [comment]
Ah, awesome, thanks! I'll just assign this to you then, so it can be closed when your change goes through.

**Comment by joachimweyl** [comment]
[PR](https://github.com/CCI-MOC/xdmod-cntr/pull/184) merged
